### ISSUE TITLE
仓库已经有几天没有成功更新了

### ISSUE THREAD

**Issue by C0j23T** [RhythmActions/PhigrosActions#1]
在Actions的日志发现了这个报错，似乎导致了这几天自动更新失败：
```
Run python3 Phigros_Extractor/GithubActions.py
[16:08:47] CRITICAL Store authenticate failed! Message:              IPA.py:212
Traceback (most recent call last):
  File "D:\a\PhigrosGameInformation\PhigrosGameInformation\Phigros_Extractor\lib\IPA\IPA.py", line 254, in handleDownload
    Store = self._get_StoreClient(args)
  File "D:\a\PhigrosGameInformation\PhigrosGameInformation\Phigros_Extractor\lib\IPA\IPA.py", line 206, in _get_StoreClient
    Store.authenticate(appleid, applepass)
  File "D:\a\PhigrosGameInformation\PhigrosGameInformation\Phigros_Extractor\lib\IPA\reqs\store.py", line 44, in authenticate
    raise StoreException("authenticate", resp.customerMessage, resp.failureType)
lib.IPA.reqs.store.StoreException: Store authenticate error: 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\a\PhigrosGameInformation\PhigrosGameInformation\Phigros_Extractor\GithubActions.py", line 158, in <module>
    Phigros = GetPhigrosIPA()
  File "D:\a\PhigrosGameInformation\PhigrosGameInformation\Phigros_Extractor\lib\IPA\IPA.py", line 299, in GetPhigrosIPA
    Phigros = IPATool().tool_main()
  File "D:\a\PhigrosGameInformation\PhigrosGameInformation\Phigros_Extractor\lib\IPA\IPA.py", line 139, in tool_main
    args.func(args)
  File "D:\a\PhigrosGameInformation\PhigrosGameInformation\Phigros_Extractor\lib\IPA\IPA.py", line 296, in handleDownload
    self._handleStoreException(e)
  File "D:\a\PhigrosGameInformation\PhigrosGameInformation\Phigros_Extractor\lib\IPA\IPA.py", line 213, in _handleStoreException
    logger.fatal("    Raw Response: %s" % (e.resp.as_dict()))
AttributeError: 'str' object has no attribute 'as_dict'
Error: Process completed with exit code 1.
```

**Comment by yuhao7370** [comment]
等我搞到一个没有2FA的apple账号

**Comment by Skyhigh173** [comment]
現在有了嗎

**Comment by C0j23T** [comment]
> 現在有了嗎

action已经在更新了，应该有了
